### ISSUE TITLE
เรียนของเก่าหรือของใหม่ดี ?

### ISSUE THREAD

**Issue by tanin-t** [tanin-t/web-dev-tutorial-for-ez#2]
คิดว่ายังไง ขอความคิดเห็นหน่อยครับ

**Comment by yoghurtpowerbear** [comment]
**ceo**
ของใหม่ครับ
###เพราะ

คนที่ยังไม่ได้ของเก่าก็ทำตาม doc
ได้ประโยชน์ทั้งคู่

**Comment by tanin-t** [comment]
ฝากให้ทุกคนเข้ามาตอบหน่อยครับ จะได้รู้ว่าสมัครบัญชิ github กันได้แล้ว

**Comment by yoghurtpowerbear** [comment]
Siri: ของใหม่ครับ 
เพราะ: จะได้รู้หลากหลายมากขึ้น และคนที่ยังไม่ได้ของเก่าแล้วมาตั้งใจเรียนของใหม่เดี๋ยวของเก่าก็เรียนเองได้

**Comment by yoghurtpowerbear** [comment]
joey  ของใหม่ครับ
เพราะ : ของ
เก่าเรียนรู้ใหม่ได้ไม่ยากถ้ามีเป้าหมาย

**Comment by yoghurtpowerbear** [comment]
`from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)


class Unit(models.Model):
    unit = models.ForeignKey(Category, on_delete=models.PROTECT)


class List(models.Model):
    list_item = models.IntegerField()
    list_list = models.CharField(max_length=100)
    list_per_unit = models.IntegerField()
    list_total = models.IntegerField()`

**Comment by yoghurtpowerbear** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>




    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    </style>

</head>

<body>

    <div id="app">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Navbar</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                            <li class="nav-item">
                                <button style="height: 65px; width: 65px;" type="button" class="btn btn-danger"
                                    data-bs-toggle="modal" data-bs-target="#exampleModal"
                                    data-bs-whatever="@mdo">+</button>
                            </li>



                    </div>
                    <p style="text-align: right;" class="display-4" id="time"></p>
                </div>
            </nav>
            <table class="table text-center">
                <thead>
                    <tr>

                        <th scope="col">#</th>
                        <th scope="col">Item</th>
                        <th scope="col">List</th>
                        <th scope="col">Per unit</th>
                        <th scope="col">Total</th>
                        <th scope="col">Remark</th>
                        <th scope="col">Category</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="col">1</th>
                        <td>1</td>
                        <td>pot</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            
                            <div class="btn-group">
                                <button id="button" type="button" class="btn btn-success dropdown-toggle"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Category
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a onclick="button('Dessert')" class="dropdown-item" href="#">Dessert</a></li>
                                    <li><a onclick="button('Vegetable')" class="dropdown-item" href="#">Vegetable</a>
                                    </li>
                                    <li><a onclick="button('Meat')" class="dropdown-item" href="#">Meat</a></li>
                                    <li><a onclick="button('Other')" class="dropdown-item  " href="#">Other</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>@fat</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td colspan="1">Larry the Bird</td>
                        <td>@twitter</td>
                    </tr>

                </tbody>
            </table>

        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="height: 500px;">
                        <form>
                            <div class="mb-3">
                                <label for="recipient-name" class="col-form-label">Item : <input v-model="item "
                                        style="width: 25%;" maxlength="3" type="text"></label>

                            </div>
                            <div class="mb-3">
                                <label for="recipient-name" class="col-form-label">List : <input v-model="lis"
                                        style="width: 80%;" type="text"></label>

                            </div>
                            <div class="mb-3 btn-group">
                                <label style="width: 50%;" id="b" for="recipient-name" class="col-form-label">Per unit :
                                    <input @input="time()" v-model="per_unit" maxlength="3" style="width: 25%;"
                                        type="text"></label>
                                <div type="button" class="dropdown">
                                    <button id="dropdown" class="btn btn-secondary dropdown-toggle" href="#"
                                        role="button" v-model="unit" id="dropdownMenuLink" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        Unit
                                    </button>

                                    <ul v-model="unit" class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <li><a onclick="dropdown('Kg.')" class="dropdown-item" href="#">Kg.</a></li>
                                        <li><a onclick="dropdown('Gram')" class="dropdown-item" href="#">G(gram)</a>
                                        </li>
                                        <li><a onclick="dropdown('Bag')" class="dropdown-item" href="#">Bag.</a></li>
                                        <li><a onclick="dropdown('Piece')" class="dropdown-item" href="#">Piece.</a>
                                        <li><a onclick="dropdown('Other')" class="dropdown-item  " href="#">Other</a>
                                        </li>
                                        </li>
                                    </ul>
                                </div>

                            </div>

                            <div class="mb-3 btn-group">
                                <label id="b" for="recipient-name" class="col-form-label">Total : <input v-model="total"
                                        maxlength="0" style="width: 25%;" type="text"></label>



                            </div>



                            <div class="mb-3">
                                <label v-model="remark" for="message-text" class="col-form-label">Remark:</label>
                                <textarea class="form-control" id="message-text"></textarea>
                            </div>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" @click="test_api()" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>






    <script>
        setInterval(() => {
            console.log('hello')
            d = new Date()
            document.getElementById("time").innerHTML = d.getDate()
                + '/' + (d.getMonth() + 1) + '/'
                + d.getUTCFullYear()
        }, 1000);

        function button(a) {
            document.getElementById("button").innerHTML = a;


        }

        function dropdown(unit) {
            document.getElementById("dropdown").innerHTML = unit;

        }



    </script>

    <script>
        var app = new Vue({
            el: '#app',
            data: {
                item: '',
                lis: '',
                per_unit: '',
                total: '',

            },
            methods: {
                time() {
                    this.total = this.item * this.per_unit
                    console.log(this.total)
                },
                test_api() {
                    data = {
                        'item': this.item,
                        'list': this.lis,
                        'per_unit': this.per_unit,
                        'total': this.total,

                    }
                    axios.post('/bill/read/', data).then(response => {
                        conosle.log(response.data.data)
                    })
                },
                
            }

        })

    </script>
    <script>
              Swal.fire({
            title: 'Do you want to save the changes?',
            showDenyButton: true,
            showCancelButton: true,
            confirmButtonText: `Save`,
            denyButtonText: `Don't save`,
        }).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {
                Swal.fire('Saved!', '', 'success')
            } else if (result.isDenied) {
                Swal.fire('Changes are not saved', '', 'info')
            }
        })
    </script>


</body>

</html>`

**Comment by yoghurtpowerbear** [comment]
`PS C:\Users\HP\OneDrive\Documents\django-joey\mysite> py manage.py makemigrations
Migrations for 'bill':
  bill\migrations\0010_auto_20210422_1403.py
    - Remove field list_category from list
    - Remove field list_date from list
    - Remove field list_remark from list
PS C:\Users\HP\OneDrive\Documents\django-joey\mysite> py manage.py migrate       
Operations to perform:
  Apply all migrations: admin, auth, bill, contenttypes, sessions
Running migrations:
  Applying bill.0007_auto_20210422_0041...Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\django\core\management\commands\migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\operations\fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "C:\Python\Python38\lib\site-packages\django\db\backends\sqlite3\schema.py", line 328, in add_field
    self._remake_table(model, create_field=field)
  File "C:\Python\Python38\lib\site-packages\django\db\backends\sqlite3\schema.py", line 189, in _remake_table
    self.effective_default(create_field)
  File "C:\Python\Python38\lib\site-packages\django\db\backends\base\schema.py", line 303, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 821, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
    value = self.get_prep_value(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1355, in get_prep_value
    value = super().get_prep_value(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1215, in get_prep_value
    return self.to_python(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1316, in to_python
    parsed = parse_datetime(value)
  File "C:\Python\Python38\lib\site-packages\django\utils\dateparse.py", line 107, in parse_datetime
    match = datetime_re.match(value)
TypeError: expected string or bytes-like object
PS C:\Users\HP\OneDrive\Documents\django-joey\mysite> py manage.py runserver     
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): bill.
Run 'python manage.py migrate' to apply them.
April 22, 2021 - 15:14:15
Django version 3.0.5, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /
[22/Apr/2021 15:14:17] "GET / HTTP/1.1" 404 2026
Not Found: /favicon.ico
[22/Apr/2021 15:14:17] "GET /favicon.ico HTTP/1.1" 404 2077
[22/Apr/2021 15:14:22] "GET /bill/list/ HTTP/1.1" 200 10834
[22/Apr/2021 15:14:24] "GET /bill/list/ HTTP/1.1" 200 10834
[22/Apr/2021 15:14:25] "GET /bill/list/ HTTP/1.1" 200 10834

Internal Server Error: /bill/read/
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python\Python38\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\OneDrive\Documents\django-joey\mysite\bill\views.py", line 17, in test_api
    List.objects.create(list_item=item['item'],
  File "C:\Python\Python38\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\django\db\models\query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python\Python38\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Python\Python38\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "C:\Python\Python38\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Python\Python38\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "C:\Python\Python38\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Python\Python38\lib\site-packages\django\db\models\sql\compiler.py", line 1390, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python\Python38\lib\site-packages\django\db\models\sql\compiler.py", line 1333, in as_sql
    value_rows = [
  File "C:\Python\Python38\lib\site-packages\django\db\models\sql\compiler.py", line 1334, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python\Python38\lib\site-packages\django\db\models\sql\compiler.py", line 1334, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python\Python38\lib\site-packages\django\db\models\sql\compiler.py", line 1275, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 821, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 816, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    raise e.__class__(
ValueError: Field 'list_item' expected a number but got ''.
[22/Apr/2021 15:14:31] "POST /bill/read/ HTTP/1.1" 500 150006
[22/Apr/2021 15:15:10] "GET /bill/list/ HTTP/1.1" 200 10900
[22/Apr/2021 15:16:39] "GET /bill/list/ HTTP/1.1" 200 10900
PS C:\Users\HP\OneDrive\Documents\django-joey\mysite> `
